### ISSUE TITLE
Message 인증방식

### ISSUE THREAD

**Issue by engolder** [EntryDSM/Cledor#9]
먼저 어드민과 일반 사용자를 구분해야한다.
이 부분에 대해 기능 명세가 명확하지 않음으로 조금 더 구체화하고,
일반 사용자도 로그인 기능을 넣을 것인지 결정한다.
어드민 사용자는 로그인 기능이 필수로 있는데, 어떤 방식으로 로그인 인증을 할 것인지 정한다.
정리하면
1. 일반 사용자, 어드민 사용자 기능 구체화
2. 일반 사용자 로그인 기능 추가여부 결정
3. 인증 방식(웹소켓, http)

**Comment by rscarrera27** [comment]
1. 끌레도르 자체가 나뚜르에 설치되는 모듈 형태이니까 유저를 구분하기 위한 목적으로 로그인을 사용하려는 거라면 나뚜르에 로컬스토리지나 쿠키에 있는 액세스 토큰을 활용하면 될거라고 생각합니다
2. 1 방식대로 가면 별도 로그인은 필요없을 것 같네요.
3. 웹소켓 핸드쉐이킹 때 토큰을 보내서 인증하는 방식을 사용하면 될거라고 생각합니다

**Comment by engolder** [comment]
그렇다면 초기에 액세스 토큰을 어떻게 받아오나요?
